name: goreleaser

on:
  create:
    tags:

jobs:
  qovery:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      -
        name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: 1.15.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      -
        name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: qoveryrd/do-k8s-token-rotate
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      -
        name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}